# Docker Compose configuratie
# Verantwoordelijke: Bart
#
# Services in deze setup:
# - flask: centrale webapplicatie voor login/dashboard
# - http: eenvoudige HTTP-server op poort 80
# - https: eenvoudige HTTPS-server op poort 443
# - ftp: FTP-server op poort 20/21 en passive poorten 30000-30010

name: itproject     # naam van het gehele project

services:
  # Centrale Flask-applicatie.
  flask:
    build: .
    container_name: itproject_flask   # Naam van Container
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data                                      # - bevat later de SQLite-database.
      - ./backups:/app/backups                                # - word gebruikt om /backups te bewaren.
      - /var/run/docker.sock:/var/run/docker.sock             # - laat de Flask-container Docker Compose aanroepen.

  # HTTP-servercontainer.
  # Wordt gebouwd vanuit servers/http.
  # Deze container toont een eenvoudige webpagina op poort 80.
  http:
    build: ./servers/http
    container_name: itproject_http     # Naam van Container
    ports:
      - "80:80"

  # HTTPS-servercontainer.
  # Wordt gebouwd vanuit servers/https.
  # Deze container gebruikt een self-signed certificaat
  # en toont een eenvoudige webpagina op poort 443.
  https:
    build: ./servers/https
    container_name: itproject_https     # Naam van Container
    ports:
      - "443:443"

  # FTP-servercontainer.
  # Wordt gebouwd vanuit servers/ftp.
  # Deze container voorziet een testgebruiker en testbestand.
  #
  # Poort 21 wordt gebruikt voor FTP-commando's.
  # Poort 20 wordt traditioneel gebruikt voor FTP-data in active mode.
  # Poorten 30000-30010 worden gebruikt voor passive FTP.
  # Dat is nodig voor clients zoals WinSCP en FileZilla.
  ftp:
    build: ./servers/ftp
    container_name: itproject_ftp     # Naam van Container
    ports:
      - "21:21"
      - "20:20"
      - "30000-30010:30000-30010"
