# HTTP nginx-configuratie
# Verantwoordelijke: Bart
#
# Deze configuratie zegt tegen nginx:
# - luister op poort 80
# - gebruik localhost als servernaam
# - toon bestanden uit /usr/share/nginx/html
# - gebruik index.html als startpagina

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
}
