# Eigenaar: Bart
# Doel:
# - nginx-configuratie voor HTTP-container
# - indexpagina aanbieden op poort 80

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
}
