# vsftpd-configuratie
# Verantwoordelijke: Bart
#
# Dit bestand bepaalt hoe de FTP-server in de container werkt.
#
# Voor de MVP willen we:
# - geen anonieme login;
# - wel login met ftpuser;
# - bestanden kunnen lezen en schrijven;
# - WinSCP/FileZilla laten werken via passive FTP.

# vsftpd draait zelf als FTP-server in deze container.
listen=YES

# Geen anonieme login. Alleen onze testgebruiker ftpuser mag aanmelden.
anonymous_enable=NO

# Laat lokale gebruikers uit de container aanmelden, zoals ftpuser.
local_enable=YES

# Laat uploads/wijzigingen toe. Zo kunnen we FTP ook echt testen.
write_enable=YES

# Nieuwe bestanden krijgen normale permissies.
local_umask=022

# Toont mapberichten als die bestaan.
dirmessage_enable=YES

# Schakelt logging van uploads/downloads in.
xferlog_enable=YES

# Active FTP gebruikt traditioneel poort 20 voor data.
connect_from_port_20=YES

# Passive FTP voor clients zoals WinSCP en FileZilla.
# Poort 21 is alleen de commandopoort.
# Voor mappenlijsten en bestanden gebruikt passive FTP extra datapoorten.
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010

# Omdat vsftpd in Docker draait, mag hij zijn interne container-IP
# niet doorgeven aan WinSCP. We testen via localhost en Docker port
# forwarding, dus geven we 127.0.0.1 door aan de FTP-client.
pasv_address=127.0.0.1

# Beperk ftpuser tot zijn eigen home-map.
chroot_local_user=YES

# Nodig omdat de home-map schrijfbaar is binnen chroot.
allow_writeable_chroot=YES

# In Alpine/Docker kan de vsftpd sandbox problemen geven.
# Voor deze MVP zetten we die uit zodat de container betrouwbaar start.
seccomp_sandbox=NO
