# vsftpd-configuratie
# Verantwoordelijke: Bart
#
# Dit bestand bepaalt hoe de FTP-server in de container werkt.
#
# Voor de MVP willen we:
# - geen anonieme login
# - wel login met lokale gebruiker ftpuser
# - bestanden kunnen lezen en schrijven
# - de gebruiker beperken tot zijn eigen map

# Laat vsftpd luisteren als standalone service.
listen=YES

# Anonieme gebruikers mogen niet aanmelden.
# Alleen de testgebruiker ftpuser mag inloggen.
anonymous_enable=NO

# Lokale Linux-gebruikers in de container mogen aanmelden.
# Hierdoor kan ftpuser gebruikt worden.
local_enable=YES

# Laat schrijfacties toe.
# Handig voor tests waarbij een bestand geüpload wordt.
write_enable=YES

# Nieuwe bestanden krijgen normale permissies.
local_umask=022

# Toont mapberichten als die bestaan.
dirmessage_enable=YES

# Schakelt logging van uploads/downloads in.
xferlog_enable=YES

# Gebruikt poort 20 voor active FTP-data.
connect_from_port_20=YES

# Beperkt de gebruiker tot zijn eigen home-map.
# Zo kan ftpuser niet zomaar door heel de container bladeren.
chroot_local_user=YES

# Nodig omdat de home-map schrijfbaar is.
# Zonder dit weigert vsftpd soms te starten in chroot-modus.
allow_writeable_chroot=YES

# In sommige Docker/Alpine-omgevingen geeft de seccomp sandbox problemen.
# Voor deze MVP schakelen we die uit zodat vsftpd betrouwbaar start.
seccomp_sandbox=NO
