# Ansible-inventory
# Verantwoordelijke: Bart
#
# Dit bestand zegt aan Ansible welke toestellen er bestaan
# en hoe Ansible later met die toestellen moet verbinden.
#
# Voor Sprint 1 voorzien we minimaal:
# - 1 router: r1
# - 1 switch: sw1
#
# De IP-adressen zijn afgestemd op onze testopstelling/EVE-NG.
# Als de topologie later wijzigt, moeten enkel deze IP's aangepast worden.

[routers]
r1 ansible_host=192.168.0.215

[switches]
sw1 ansible_host=192.168.0.216



# Deze groep bundelt alle netwerktoestellen.
# Daardoor kunnen gedeelde instellingen hieronder 1 keer gezet worden
# in plaats van apart bij routers en switches.

[network_devices:children]
routers
switches

# Gedeelde verbindingsinstellingen voor routers en switches.
#
# network_cli wordt gebruikt voor netwerkapparaten zoals Cisco routers/switches.
# cisco.ios.ios zegt tegen Ansible dat het om Cisco IOS-toestellen gaat.
#
# De login hieronder is voorlopig een placeholder.
# Bij een echte EVE-NG-test passen we username/password aan naar de labotoestellen.

[network_devices:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_network_cli_ssh_type=paramiko
ansible_user=admin
ansible_password=azerty
ansible_become=no
ansible_command_timeout=120
ansible_connect_timeout=60
ansible_ssh_common_args='-oKexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa'
