# Hier komt de Ansible-inventory.
# Verantwoordelijke: Bart
#
# Doel:
# - router(s) en switch(es) definiëren waarop Ansible werkt
# - later juiste IP-adressen, gebruikersnaam en verbindingsmethode invullen
#
# Vaste structuur:
# - groep [routers] blijft bestaan
# - groep [switches] blijft bestaan
# - minimaal r1 en sw1 voorzien voor de MVP
# - zie docs/koppelafspraken.md

[routers]
 r1 ansible_host=192.168.0.215

[switches]
 sw1 ansible_host=192.168.0.216
