# Ansible-inventory voor setup2
# Verantwoordelijke: Bart
#
# Deze inventory hoort bij de labo-podopstelling uit Brussel.
# Setup2 gebruikt een eigen inventory, zodat de management-IP's
# niet moeten overeenkomen met setup1.

[routers]
r1 ansible_host=192.168.0.221

[pod_switches]
sw11 ansible_host=192.168.0.222
sw12 ansible_host=192.168.0.223

[distribution_switches]
distsw ansible_host=192.168.0.224

[classroom_switches]
classsw ansible_host=192.168.0.225

[switches:children]
pod_switches
distribution_switches
classroom_switches

[network_devices:children]
routers
switches

[network_devices:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_network_cli_ssh_type=paramiko
ansible_user=admin
ansible_password=azerty
ansible_become=no
ansible_command_timeout=120
ansible_connect_timeout=60
ansible_ssh_common_args='-oKexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa'
