# Ansible-inventory voor setup2
# Verantwoordelijke: Bart
#
# Deze inventory hoort bij de labo-podopstelling uit Brussel.

# Router van de pod.
[routers]
r1 ansible_host=192.168.0.221

# De 2 switches die in de pod zelf staan.
[pod_switches]
sw11 ansible_host=192.168.0.222
sw12 ansible_host=192.168.0.223

# Switch aan de pod/serverruimte-kant.
[distribution_switches]
distsw ansible_host=192.168.0.224

# Switch aan de classroomkant.
[classroom_switches]
classsw ansible_host=192.168.0.225

# We bundelen alle switchgroepen in 1 groep.
# Daardoor kan switch.yml gewoon op "switches" draaien.
[switches:children]
pod_switches
distribution_switches
classroom_switches

# We stoppen routers en switches in 1 groep.
# Daardoor kunnen we de verbindingsinstellingen hieronder 1 keer zetten
# in plaats van apart bij elk toestel.
[network_devices:children]
routers
switches

[network_devices:vars]
# Ansible moet deze toestellen behandelen als netwerktoestellen.
# Daardoor gebruikt Ansible geen gewone Linux-SSH, maar Cisco CLI-commando's.
ansible_connection=network_cli

# Dit zegt aan Ansible dat het om Cisco IOS-toestellen gaat.
ansible_network_os=cisco.ios.ios

# We gebruiken Paramiko als SSH-methode.
# Dit werkte het beste met onze Cisco IOSv-toestellen in EVE-NG.
# Een alternatief is libssh, maar bij onze labo-opstelling was Paramiko eenvoudiger en stabieler.
ansible_network_cli_ssh_type=paramiko

# Gebruikersnaam waarmee Ansible inlogt op de router en switch.
ansible_user=admin

# Wachtwoord van de admin-gebruiker.
ansible_password=azerty

# Ansible moet na het inloggen geen extra enable-stap doen.
# Onze admin-gebruiker heeft privilege 15 en krijgt dus meteen genoeg rechten.
ansible_become=no

# Hoe lang Ansible mag wachten op een antwoord van een commando.
ansible_command_timeout=120

# Hoe lang Ansible mag proberen om verbinding te maken met het toestel.
ansible_connect_timeout=60


# Sommige Cisco IOSv-images gebruiken oudere SSH-algoritmes.
# Moderne SSH-clients blokkeren die soms standaard.
# Daarom laten we deze oudere algoritmes bewust toe voor onze EVE-NG labo-opstelling.
#
# KexAlgorithms:
# bepaalt hoe de SSH-verbinding in het begin veilig wordt opgezet.
# We laten oude Diffie-Hellman-methodes toe omdat Cisco IOSv die nog gebruikt.
#
# HostKeyAlgorithms:
# bepaalt welk type sleutel van het Cisco-toestel aanvaard wordt.
# We laten ssh-rsa toe omdat oudere Cisco-images vaak zo'n RSA-hostkey gebruiken.
#
# PubkeyAcceptedAlgorithms:
# bepaalt welke publieke sleutel-algoritmes SSH mag gebruiken.
# Ook hier laten we ssh-rsa toe omdat dit beter werkt met oudere Cisco IOSv-images.
#
# In een echte productieomgeving zou je liever modernere SSH-algoritmes gebruiken.
ansible_ssh_common_args='-oKexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa'
